### ISSUE TITLE
Feature request: provide separate input paths for pgen, psam, pvar, lanc

### ISSUE THREAD

**Issue by michaelofrancis** [KangchengHou/admix-kit#30]
Hi,

Right now user is only able to load in pfile and lanc when they all have the same stem and are in the same directory. This is inconvenient and it would be really great to be able to load in separate file paths for each if desired. This applies to most/all of the existing functions.

Thanks,
Mike

**Comment by KangchengHou** [comment]
.lanc files always being coupled with .pgen / .psam / .pvar files is designed in the same spirit that PLINK2 files always come in triples. It would require many changes to the command line interface to incorporate the feature that .lanc can be loaded seperately - currently sorry that I do not have enough bandwidth to incorporate this. As a quick fix, I suggest to have soft link `ln -s` to link `.lanc` files from other directories.

**Comment by michaelofrancis** [comment]
Hi, I imagine most researchers will have dedicated directories for pfiles that they will not want to add .lanc files to. I suppose I could create a directory which has symlinks for all four of the files and this would be fine. Thank you.
